// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL1dswYVN_0jb3WGmZYTOBtEBdKTFvqU8',
    appId: '1:679600547007:web:1b154970221edef96d920a',
    messagingSenderId: '679600547007',
    projectId: 'todo-78758',
    authDomain: 'todo-78758.firebaseapp.com',
    storageBucket: 'todo-78758.appspot.com',
    measurementId: 'G-CZ7SVX7N7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs-F5vB4OleMQ-Rd6DkocXWGpPraqhjlo',
    appId: '1:679600547007:android:b140ccef989dd8ba6d920a',
    messagingSenderId: '679600547007',
    projectId: 'todo-78758',
    storageBucket: 'todo-78758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhp30yEa5EDrnWwwhHPu6Y29tpQWGwso',
    appId: '1:679600547007:ios:77124165b8bb0fd16d920a',
    messagingSenderId: '679600547007',
    projectId: 'todo-78758',
    storageBucket: 'todo-78758.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhp30yEa5EDrnWwwhHPu6Y29tpQWGwso',
    appId: '1:679600547007:ios:f4308729ecaa82726d920a',
    messagingSenderId: '679600547007',
    projectId: 'todo-78758',
    storageBucket: 'todo-78758.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
